 
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # HTTP          
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
