name: CI Pipeline

on:
  pull_request:  
    branches:
      - main    
      - develop 
  push:          
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Debug  # Используем Debug, чтобы проверить все тесты
    
    - name: Debug: List all files in workspace
      run: ls -R /home/runner/work/Final-Task/Final-Task/

    - name: Debug: List test output directory
      run: ls -la /home/runner/work/Final-Task/Final-Task/Trenning_NotificationsExample.Tests/bin/Debug/net8.0/

    - name: Run tests
      run: dotnet test Trenning_NotificationsExample.Tests/Trenning_NotificationsExample.Tests.csproj --no-build --verbosity normal
